### ISSUE TITLE
Payment methods: document how to setup each method

### ISSUE THREAD

**Issue by real34** [front-commerce/developers.front-commerce.com#47]
Gather documentation from our old tools, and update this issue with relevant documentation information before adding them to official developers documentation.

List all the supported payment methods and how to configure them (in payment backoffice, magento admin, service keys, etc.)

---

Some notes:

## Front-Commerce embedded payments modules

Front-Commerce can handle payments directly with its middleware, without the need for a payment integration in your e-commerce system.

We provide the necessary payment method implementation for your eCommerce solution, so that you can still benefit from order management and workflows.

For your eCommerce system, a payment made with Front-Commerce is integrated in a similar way than checks / wire payments (sometimes named "offline payment"). The difference is that due to possible API integrations, Front-Commerce will still mark the order payment as validated upon receiving automatic notifications from the payment service.

WARNING: TODO - Add an architecture graph here

Below are the existing Front-Commerce payment modules.

### Production ready

The modules below are used in production and ready for use.

- [Ingenico FlexCheckout (Ogone)](https://payment-services.ingenico.com/int/en/ogone/support/guides/integration%20guides/flexcheckout)

### Working

The modules below have been developed and are ready for use, but not yet used in production by customers.

- [Paypal Checkout button](https://developer.paypal.com/docs/checkout/)

### Started

The modules below have been started but are still in progress.

- [PayZen](https://payzen.io/en-EN/cards/rest-api/V3/web-services/) - paused due to unfinished remote API and no more use case

### Planned

The modules below are planned to be implemented in our roadmap. Please contact us if you need a payment to be supported.

- Stripe

**TODO Document configuration**

## Magento2 supported modules

The Magento2 modules below are supported by Front-Commerce’s core. Configuration is the same than for a standard Magento installation.

### Production ready

The modules below are used in production and ready for use.

- [PayPal Express](https://docs.magento.com/m2/ce/user_guide/payment/paypal-express-checkout.html) (Magento2 core feature)
- [PayZen](https://payzen.io/en-EN/free-payment-plugins/magento2/sitemap.html)
- [Ingenico ePayments Ogone](https://epayments.developer-ingenico.com/documentation/ecommerce-extensions/magento-2/)

### Working

The modules below have been developed and are ready for use, but not yet used in production by customers.

- [Adyen](https://docs.adyen.com/developers/plugins/magento-2?redirect) - HPP mode only

**Comment by real34** [comment]
## Stripe

```diff
// .env
+# Stripe payment
+# API Keys from https://dashboard.stripe.com/account/apikeys
+FRONT_COMMERCE_WEB_STRIPE_PUBLISHABLE_KEY=pk_xxxxxx
+FRONT_COMMERCE_STRIPE_SECRET_KEY=sk_xxxxxx
```

```diff
// .front-commerce.js
   modules: [],
   serverModules: [
     { name: "FrontCommerceCore", path: "server/modules/front-commerce-core" },
-    { name: "Magento2", path: "server/modules/magento2" }
+    { name: "Magento2", path: "server/modules/magento2" },
+    { name: "Stripe", path: "server/modules/payment-stripe" }
   ]
```

**Comment by JulienPradet** [comment]
## PayZen Embedded

### Configure your environment

> WIP

### Register the PayZen payment module

In your Front-Commerce application:

```diff
// .front-commerce.js
   modules: [],
   serverModules: [
     { name: "FrontCommerceCore", path: "server/modules/front-commerce-core" },
-    { name: "Magento2", path: "server/modules/magento2" }
+    { name: "Magento2", path: "server/modules/magento2" },
+    { name: "PayZen", path: "server/modules/payment-payzen" }
   ]
```

### Register your PayZen payment component

1. Override the file that lets you register additional payments forms in Front-Commerce

```
mkdir -p my-module/web/theme/modules/Checkout/Payment/AdditionalPaymentInformation/
cp -u node_modules/front-commerce/src/web/theme/modules/Checkout/Payment/AdditionalPaymentInformation/getAdditionalDataComponent.js my-module/web/theme/modules/Checkout/Payment/AdditionalPaymentInformation/getAdditionalDataComponent.js
```

2. Register PayZen

```diff
+import PayZenEmbeddedForm from "./PayZenEmbeddedForm";

const ComponentMap = {
+  payzen_embedded: PayZenEmbeddedForm
};
```

### Update your CSPs

To allow loading PayZen related remote resources:

```diff
// my-module/config/website.js
  contentSecurityPolicy: {
    directives: {
-      scriptSrc: [],
-      frameSrc: [],
-      styleSrc: [],
-      imgSrc: [],
+      scriptSrc: ["api.lyra.com", "api.payzen.eu"],
+      frameSrc: ["api.payzen.eu"],
+      styleSrc: ["api.lyra.com", "api.payzen.eu"],
+      imgSrc: ["api.payzen.eu"],
      styleSrc: [],
      imgSrc: [],
      connectSrc: [],
      baseUri: []
    }
  },
```

**Comment by JulienPradet** [comment]
## Ogone

### Configure your environment

> WIP

### Register the Ogone payment module

In your Front-Commerce application:

```diff
// .front-commerce.js
   modules: [],
   serverModules: [
     { name: "FrontCommerceCore", path: "server/modules/front-commerce-core" },
-    { name: "Magento2", path: "server/modules/magento2" }
+    { name: "Magento2", path: "server/modules/magento2" },
+    { name: "Ogone", path: "server/modules/payment-ogone" }
   ]
```

### Register your Ogone payment component

1. Override the file that lets you register additional payments forms in Front-Commerce

```
mkdir -p my-module/web/theme/modules/Checkout/Payment/AdditionalPaymentInformation/
cp -u node_modules/front-commerce/src/web/theme/modules/Checkout/Payment/AdditionalPaymentInformation/getAdditionalDataComponent.js my-module/web/theme/modules/Checkout/Payment/AdditionalPaymentInformation/getAdditionalDataComponent.js
```

2. Register Ogone

```diff
+import OgoneFlexCheckoutForm from "./OgoneFlexCheckoutForm";

const ComponentMap = {
+  ogone_flexcheckout: OgoneFlexCheckoutForm
};
```

### Update your CSPs

To allow loading Ogone related remote resources:

```diff
// my-module/config/website.js
  contentSecurityPolicy: {
    directives: {
      scriptSrc: [],
-      frameSrc: [],
+      frameSrc: ["secure.ogone.com", "ogone.test.v-psp.com"],
      styleSrc: [],
      imgSrc: [],
      connectSrc: [],
      baseUri: []
    }
  },
```

**Comment by JulienPradet** [comment]
## Paypal

### Configure your environment

> WIP

### Register the Paypal payment module

In your Front-Commerce application:

```diff
// .front-commerce.js
   modules: [],
   serverModules: [
     { name: "FrontCommerceCore", path: "server/modules/front-commerce-core" },
-    { name: "Magento2", path: "server/modules/magento2" }
+    { name: "Magento2", path: "server/modules/magento2" },
+    { name: "Ogone", path: "server/modules/payment-paypal" }
   ]
```

### Register your Ogone payment component

1. Override the file that lets you register additional payments forms in Front-Commerce

```
mkdir -p my-module/web/theme/modules/Checkout/Payment/AdditionalPaymentInformation/
cp -u node_modules/front-commerce/src/web/theme/modules/Checkout/Payment/AdditionalPaymentInformation/getAdditionalDataComponent.js my-module/web/theme/modules/Checkout/Payment/AdditionalPaymentInformation/getAdditionalDataComponent.js
```

2. Register Paypal

```diff
+import PaypalButton from "./PaypalButton";

const ComponentMap = {
+  paypal_button: PaypalButton
};
```

### Update your CSPs

> WIP

**Comment by real34** [comment]
## Data customization.

Stripe: see https://gitlab.com/front-commerce/front-commerce/issues/165#note_178152917

Paypal, Payzen: document data transforms available
