### ISSUE TITLE
Migration guides: dead link

### ISSUE THREAD

**Issue by VincentMarmiesse** [front-commerce/developers.front-commerce.com#60]
URL: https://developers.front-commerce.com/docs/

> Last but not least, if you are upgrading a project to the latest Front-Commerce version, we have documented some Migration guides to make the process as seamless as possible.

The link on `Migration guides` leads to `https://developers.front-commerce.com/docs/migration-guides.md` but throws a 404 error.

**Comment by real34** [comment]
Thanks! It’s fixed.
